version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  test:
    parallelism: 1
    resource_class: small
    docker:
      - image: cimg/ruby:2.6.6-browsers
    steps:
      - checkout
      - restore_cache:
          key: integration-tests-{{ checksum "Gemfile.lock" }}-v1 # increment v number to bust cache
      - run:
          name: Ensure local bin directory exists
          command: mkdir -p ~/.local/bin
      - run:
          # Firefox needs to be available from /usr/local/bin or else the Orb will re-install it
          name: Restore Firefox installation from cache (if in cache)
          command: |
            if [ -e ~/.local/bin/firefox ]
            then
              sudo cp -P ~/.local/bin/firefox /usr/local/bin/firefox
            fi
      - browser-tools/install-firefox:
          install-dir: /home/circleci/.local/bin
      - run:
          # Copy the Firefox symlink back into ~/.local/bin so it persists to the cache
          name: Put Firefox installation into the local bin directory
          command: cp -P /usr/local/bin/firefox ~/.local/bin/firefox
      - browser-tools/install-geckodriver:
          install-dir: /home/circleci/.local/bin
      - run: bundle config set path 'vendor/bundle'
      - run: bundle check || bundle install
      - save_cache:
          key: integration-tests-{{ checksum "Gemfile.lock" }}-v1 # increment v number to bust cache
          paths:
            - vendor/bundle
            - ~/.local/bin
      - run: bundle exec rspec spec/integration --format documentation --format RspecJunitFormatter -o screenshots/rspec.xml
      - store_test_results:
          path: screenshots
      - store_artifacts:
          path: screenshots
workflows:
  commit:
    jobs:
      - test
  threehourly:
    triggers:
      - schedule:
          cron: 30 0,3,6,9,12,15,18,21 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - test
