version: 2
jobs:
  test:
    parallelism: 1
    working_directory: ~/offender-management-integration-tests
    resource_class: small
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - run:
          name: install firefox
          command: |
            wget -L "https://ftp.mozilla.org/pub/firefox/releases/$FIREFOX_VERSION/linux-x86_64/en-US/firefox-$FIREFOX_VERSION.tar.bz2" -O "firefox-$FIREFOX_VERSION.tar.bz2"
            tar xjf "firefox-$FIREFOX_VERSION.tar.bz2"
            sudo rm -rf /opt/firefox
            sudo mv firefox /opt/
            sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
      - run:
          name: install geckodriver
          command: |
            wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
            tar -zxvf geckodriver-v0.24.0-linux64.tar.gz
            sudo mv geckodriver /usr/local/bin/
      - run: bundle exec rspec spec/integration --no-color --format documentation --format RspecJunitFormatter -o screenshots/rspec.xml
      - save_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - store_test_results:
          path: screenshots
      - store_artifacts:
          path: screenshots
workflows:
  version: 2
  commit:
    jobs:
      - test
  threehourly:
    triggers:
      - schedule:
          cron: 30 0,3,6,9,12,15,18,21 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - test
